Update gen5.yml

diff --git a/.github/workflows/gen5.yml b/.github/workflows/gen5.yml
--- a/.github/workflows/gen5.yml
+++ b/.github/workflows/gen5.yml
@@ -177,6 +177,14 @@ jobs:
           name: appstream-helper
           path: ${{ github.workspace }}/.local/bin
 
+      - name: Verify appstream-helper is downloaded
+        run: |
+          ls -l ${{ github.workspace }}/.local/bin
+          if [ ! -f ${{ github.workspace }}/.local/bin/appstream-helper ]; then
+            echo "appstream-helper not found!"
+            exit 1
+          fi
+
       - name: Generate metadata
         run: |
           set -x
