Update gen5.yml

diff --git a/.github/workflows/gen5.yml b/.github/workflows/gen5.yml
--- a/.github/workflows/gen5.yml
+++ b/.github/workflows/gen5.yml
@@ -15,8 +15,8 @@ on:
         default: "true"
 
 jobs:
-  build_and_publish:
-    name: Build, Publish AppBundles and Metadata
+  build:
+    name: Build and Publish AppBundles
     runs-on: ubuntu-latest
     permissions: write-all
     container:
@@ -47,6 +47,14 @@ jobs:
           cd ./pelf/cmd/misc/appstream_helper
           go install .
 
+      - name: Verify appstream-helper binary
+        run: |
+          if [ ! -f "${{ env.GOBIN }}/appstream-helper" ]; then
+            echo "appstream-helper binary not found!"
+            exit 1
+          fi
+          chmod +x "${{ env.GOBIN }}/appstream-helper"
+
       - name: Set OUT_DIR environment variable
         run: |
           OUT_DIR="$GITHUB_WORKSPACE/APPBUNDLES"
@@ -55,8 +63,15 @@ jobs:
           echo "OUT_DIR=${OUT_DIR}" >> $GITHUB_ENV
           echo "META_OUT_DIR=${META_OUT_DIR}" >> $GITHUB_ENV
 
+      - name: List available scripts
+        run: |
+          echo "Listing available recipes:"
+          tree "$GITHUB_WORKSPACE/recipes"
+
       - name: Run selected build scripts
         run: |
+          ls "$GITHUB_WORKSPACE/baseSystems"
+          set -x
           export PATH="$GITHUB_WORKSPACE/baseSystems:$PATH"
           echo "PATH=$PATH" >> $GITHUB_ENV
 
@@ -80,8 +95,22 @@ jobs:
         run: |
           set -x
           wget "https://huggingface.co/datasets/pkgforge/pkgcache/resolve/main/FLATPAK_APPSTREAM.xml"
-          chmod +x ${{ github.workspace }}/.local/bin/appstream-helper
-          ${{ github.workspace }}/.local/bin/appstream-helper --components-xml ./FLATPAK_APPSTREAM.xml --input-dir "${{ github.workspace }}" --output-dir "${{ github.workspace }}/APPBUNDLES_META" --output-file "${{ github.workspace }}/APPBUNDLES_META/metadata.json" --download-url-prefix "https://github.com/xplshn/AppBundleHUB/releases/download/${{ env.TAG_NAME }}/" --metadata-prefix "https://github.com/xplshn/AppBundleHUB/releases/download/latest_metadata/"
+          chmod +x ${{ env.GOBIN }}/appstream-helper
+          ${{ env.GOBIN }}/appstream-helper --components-xml ./FLATPAK_APPSTREAM.xml --input-dir "${{ github.workspace }}" --output-dir "${{ github.workspace }}/APPBUNDLES_META" --output-file "${{ github.workspace }}/APPBUNDLES_META/metadata.json" --download-url-prefix "https://github.com/xplshn/AppBundleHUB/releases/download/${{ env.TAG_NAME }}/" --metadata-prefix "https://github.com/xplshn/AppBundleHUB/releases/download/latest_metadata/"
+
+      - name: Manage Tags
+        if: ${{ github.event.inputs.release == 'true' }}
+        run: |
+          git fetch --tags
+          TAGS=$(git tag | grep -v "^latest_metadata$" | sort -V)
+          TAG_COUNT=$(echo "$TAGS" | wc -l)
+          if [ "$TAG_COUNT" -gt 5 ]; then
+            TAGS_TO_DELETE=$(echo "$TAGS" | head -n -1)
+            for TAG in $TAGS_TO_DELETE; do
+              git tag -d "$TAG"
+              git push origin --delete "$TAG"
+            done
+          fi
 
       - name: Create Git Tag
         if: ${{ github.event.inputs.release == 'true' }}
@@ -91,16 +120,54 @@ jobs:
           git push origin "$TAG_NAME"
           echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
 
-      - name: Create Release for AppBundles and Metadata
+      - name: Determine if pre-release
+        id: determine_prerelease
+        run: |
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+            echo "prerelease=true" >> $GITHUB_ENV
+          else
+            echo "prerelease=false" >> $GITHUB_ENV
+          fi
+
+      - name: Create Release
         if: ${{ github.event.inputs.release == 'true' }}
         uses: softprops/action-gh-release@v2.0.8
         with:
           name: "Weekly Release - ${{ env.TAG_NAME }}"
           tag_name: "${{ env.TAG_NAME }}"
+          prerelease: ${{ env.prerelease }}
           draft: false
-          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
+          generate_release_notes: false
           make_latest: true
           files: |
-            ${{ env.OUT_DIR }}/*.AppBundle
+            ${{ github.workspace }}/*.AppBundle
             ${{ github.workspace }}/APPBUNDLES_META/metadata.json
         continue-on-error: true
+
+      - name: Update latest_metadata tag and create release
+        if: ${{ github.event.inputs.release == 'true' }}
+        run: |
+          ls -FA
+          git fetch --tags
+          if git tag -l | grep -q "^latest_metadata$"; then
+            git tag -d latest_metadata
+            git push origin --delete latest_metadata || true
+          fi
+          git tag latest_metadata
+          git push origin latest_metadata
+
+      - name: Create Release for Metadata
+        if: ${{ github.event.inputs.release == 'true' }}
+        uses: softprops/action-gh-release@v2.0.8
+        with:
+          name: "Latest Metadata"
+          tag_name: "latest_metadata"
+          files: |
+            ${{ github.workspace }}/*.json
+            ${{ github.workspace }}/*.png
+            ${{ github.workspace }}/*.svg
+            ${{ github.workspace }}/*.desktop
+            ${{ github.workspace }}/*.xml
+          draft: false
+          prerelease: true
+          make_latest: false
