Update gen5.yml

diff --git a/.github/workflows/gen5.yml b/.github/workflows/gen5.yml
--- a/.github/workflows/gen5.yml
+++ b/.github/workflows/gen5.yml
@@ -94,8 +94,8 @@ jobs:
           name: app-bundles
           path: ${{ env.OUT_DIR }}/*.AppBundle
 
-  release:
-    name: Release AppBundles
+  publish_appbundles:
+    name: Publish AppBundles
     runs-on: ubuntu-latest
     needs: build
     permissions: write-all
@@ -109,6 +109,27 @@ jobs:
         with:
           name: app-bundles
           path: ${{ github.workspace }}
+
+      - name: Download appstream-helper artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: appstream-helper
+          path: ${{ github.workspace }}/.local/bin
+
+      - name: Verify appstream-helper is downloaded
+        run: |
+          ls -l ${{ github.workspace }}/.local/bin
+          if [ ! -f ${{ github.workspace }}/.local/bin/appstream-helper ]; then
+            echo "appstream-helper not found!"
+            exit 1
+          fi
+
+      - name: Generate metadata
+        run: |
+          set -x
+          wget "https://huggingface.co/datasets/pkgforge/pkgcache/resolve/main/FLATPAK_APPSTREAM.xml"
+          chmod +x ${{ github.workspace }}/.local/bin/appstream-helper
+          ${{ github.workspace }}/.local/bin/appstream-helper --components-xml ./FLATPAK_APPSTREAM.xml --input-dir "${{ github.workspace }}" --output-dir "${{ github.workspace }}/APPBUNDLES_META" --output-file "${{ github.workspace }}/APPBUNDLES_META/metadata.json" --download-url-prefix "https://github.com/xplshn/AppBundleHUB/releases/download/${{ env.TAG_NAME }}/" --metadata-prefix "https://github.com/xplshn/AppBundleHUB/releases/download/latest_metadata/"
 
       - name: Manage Tags
         if: ${{ github.event.inputs.release == 'true' }}
@@ -153,55 +174,13 @@ jobs:
           make_latest: true
           files: |
             ${{ github.workspace }}/*.AppBundle
+            ${{ github.workspace }}/APPBUNDLES_META/*
         continue-on-error: true
-
-  generate_metadata:
-    name: Generate Metadata
-    runs-on: ubuntu-latest
-    needs: release
-    permissions: write-all
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Download app bundle artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: app-bundles
-          path: ${{ github.workspace }}
-
-      - name: Download appstream-helper artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: appstream-helper
-          path: ${{ github.workspace }}/.local/bin
-
-      - name: Verify appstream-helper is downloaded
-        run: |
-          ls -l ${{ github.workspace }}/.local/bin
-          if [ ! -f ${{ github.workspace }}/.local/bin/appstream-helper ]; then
-            echo "appstream-helper not found!"
-            exit 1
-          fi
-
-      - name: Generate metadata
-        run: |
-          set -x
-          wget "https://huggingface.co/datasets/pkgforge/pkgcache/resolve/main/FLATPAK_APPSTREAM.xml"
-          chmod +x ${{ github.workspace }}/.local/bin/appstream-helper
-          ${{ github.workspace }}/.local/bin/appstream-helper --components-xml ./FLATPAK_APPSTREAM.xml --input-dir "${{ github.workspace }}" --output-dir "${{ github.workspace }}/APPBUNDLES_META" --output-file "${{ github.workspace }}/APPBUNDLES_META/metadata.json" --download-url-prefix "https://github.com/xplshn/AppBundleHUB/releases/download/${{ env.TAG_NAME }}/" --metadata-prefix "https://github.com/xplshn/AppBundleHUB/releases/download/latest_metadata/"
-
-      - name: Upload metadata artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: metadata
-          path: ${{ github.workspace }}/APPBUNDLES_META/*
 
   publish_metadata:
     name: Publish Metadata
     runs-on: ubuntu-latest
-    needs: generate_metadata
+    needs: publish_appbundles
     if: ${{ github.event.inputs.release == 'true' }}
     permissions: write-all
     steps:
